# Generated by Django 5.1.1 on 2024-10-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_reservation_dropoff_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dropoff_location',
            field=models.CharField(choices=[('lucena_grand_terminal_drop', 'Lucena Grand Terminal'), ('groto_lucban_quezon_drop', 'Groto Lucban Quezon'), ('tayabas_city_quezon_drop', 'Tayabas City Quezon')], max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_location',
            field=models.CharField(choices=[('lucena_grand_terminal_pick', 'Lucena Grand Terminal'), ('groto_lucban_quezon_pick', 'Groto Lucban Quezon'), ('tayabas_city_quezon_pick', 'Tayabas City Quezon')], max_length=255),
        ),
    ]
